let colecaoSignos = [
    { "Nome": "Aquário", "DataInicio": "01-20", "DataFim": "02-18", "Descricao": "Independente, o aquariano preza muito por sua liberdade. Gosta de viajar, sair e conhecer pessoas novas. Tem uma mente aberta e gosta de tudo o que é inovador e moderno, desde roupas e tecnologia, até mesmo atitudes comportamentais." },
    { "Nome": "Peixes", "DataInicio": "02-19", "DataFim": "03-20", "Descricao": "Este é o signo mais romântico do zodíaco. Sonhador e carinhoso, ele está sempre preocupado com o bem estar dos outros. Sensível e carinhoso, acredita em contos de fadas e acha que todos merecem um final feliz." },
    { "Nome": "Áries", "DataInicio": "03-21", "DataFim": "04-19", "Descricao": "Impulsivo, o ariano não pensa muito sobre seus atos. É aquele que primeiro age, depois reflete. Agitado, precisa de muita atividade para gastar a energia, senão pode ficar agressivo e explosivo." },
    { "Nome": "Touro", "DataInicio": "04-20", "DataFim": "05-20", "Descricao": "Teimoso, o taurino é determinado e protetor. Precisa de segurança e estabilidade para ser feliz, e conquista isso com muito trabalho e concentração. Carinhoso, o taurino pode ser ciumento com quem ama." },
    { "Nome": "Gêmeos", "DataInicio": "05-21", "DataFim": "06-21", "Descricao": "Espontâneo e um pouco instável, o geminiano é uma verdadeira caixinha de surpresas. Como é volátil, muitas vezes nem mesmo o geminiano se entende, mas o importante é que ele está sempre de bom humor e em busca de aventuras." },
    { "Nome": "Câncer", "DataInicio": "06-22", "DataFim": "07-23", "Descricao": "Família é a palavra-chave para o canceriano. Tranquilo e emotivo, gosta de ficar em casa, fazer programas com quem ama e curtir momentos com os parentes. Curioso, faz amizade com facilidade, mas pode ser um pouco sensível." },
    { "Nome": "Leão", "DataInicio": "07-24", "DataFim": "08-22", "Descricao": "Este é signo que veio para brilhar. O leonino gosta de chamar a atenção e ser o centro do mundo, mas também é muito amável e leal. Simpático e comunicativo, o nativo de leão pode ser um pouco ciumento e inseguro." },
    { "Nome": "Virgem", "DataInicio": "08-23", "DataFim": "09-22", "Descricao": "Perspicaz e inteligente, o virginiano está acostumado com o sucesso, por isso se cobra muito, assim como aos demais. Por isso, pode ser um pouco rígido e magoar quem ama. Tímido, prefere programas tranquilos a grandes eventos." },
    { "Nome": "Libra", "DataInicio": "09-23", "DataFim": "10-22", "Descricao": "O libriano gosta do que é belo e harmonioso. Não gosta de conflitos e por isso tenta ser imparcial em debates e brigas. Indeciso, pode demorar muito para escolher coisas simples, como o que comer ou vestir. Bom gosto define este signo." },
    { "Nome": "Escorpião", "DataInicio": "10-23", "DataFim": "11-21", "Descricao": "Determinado, o escorpiano vai até o fim para conquistar os seus objetivos. Sensual e romântico, gosta de estar em relacionamentos, mas pode ser desconfiado enquanto não se sentir seguro com a pessoa." },
    { "Nome": "Sagitário", "DataInicio": "11-22", "DataFim": "12-21", "Descricao": "Um signo de bem com a vida, que está sempre em busca de ação e que vive rodeado de amigos. Este é o signo de sagitário, que é sonhador e adora conhecer pessoas e lugares novos." },
    { "Nome": "Capricórnio", "DataInicio": "12-22", "DataFim": "01-19", "Descricao": "Trabalhador, tímido e educado, o capricórnio pode passar uma imagem de fechado e até mesmo antipático, mas é que ele eprecisa confiar em quem está ao seu lado para se abrir totalmente. Com paciência, ele se mostra um amigo leal e um companheiro fiel." }
];

export default colecaoSignos;